<?php

return [
    /*
    |--------------------------------------------------------------------------
    | API Domain 
    |--------------------------------------------------------------------------
    |
    | This is the url where all the endpoints originates from. 
    */

    'apiUrl' => env('MPESA_ENV', 'sandbox') === 'production' 
        ? 'https://api.safaricom.co.ke/'
        : 'https://sandbox.safaricom.co.ke/',

    /*
    |--------------------------------------------------------------------------
    | Status
    |--------------------------------------------------------------------------
    |
    | This determines the state of the package, whether to use in sandbox mode or not.
    |
    */

    'is_sandbox' => env('MPESA_ENV', 'sandbox') !== 'production',

    /*
    |--------------------------------------------------------------------------
    | Credentials
    |--------------------------------------------------------------------------
    |
    | These are the credentials to be used to transact with the M-Pesa API
    */

    'apps' => [
        'default' => [
            'consumer_key' => env('MPESA_CONSUMER_KEY'),
            'consumer_secret' => env('MPESA_CONSUMER_SECRET'),
        ],
        'bulk' => [
            'consumer_key' => env('MPESA_BULK_CONSUMER_KEY', ''),
            'consumer_secret' => env('MPESA_BULK_CONSUMER_SECRET', ''),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | File Cache Location
    |--------------------------------------------------------------------------
    |
    | This will be the location on the disk where the caching will be done.
    |
    */

    'cache_location' => storage_path('framework/cache/mpesa'),

    /*
    |--------------------------------------------------------------------------
    | Callback Method
    |--------------------------------------------------------------------------
    |
    | This is the request method to be used on the Callback URL on communication
    | with your server.
    |
    | e.g. GET | POST
    |
    */

    'callback_method' => 'POST',

    /*
    |--------------------------------------------------------------------------
    | LipaNaMpesa API Online Config
    |--------------------------------------------------------------------------
    |
    | This is a fully qualified endpoint that will be be queried by Safaricom's
    | API on completion or failure of the transaction.
    |
    */
    'lnmo' => [
        /*
        |--------------------------------------------------------------------------
        | Paybill Number
        |--------------------------------------------------------------------------
        |
        | This is a registered Paybill Number that will be used as the Merchant ID
        | on every transaction. This is also the account to be debited.
        |
        */
        'short_code' => env('MPESA_SHORTCODE', 174379),

        /*
        | STK Push callback URL
        |--------------------------------------------------------------------------
        |
        | This is a fully qualified endpoint that will be queried by Safaricom's
        | API on completion or failure of a push transaction.
        |
        */
        'callback' => env('MPESA_STK_CALLBACK_URL'),
        
        /*
        |--------------------------------------------------------------------------
        | SAG Passkey
        |--------------------------------------------------------------------------
        |
        | This is the secret SAG Passkey generated by Safaricom on registration
        | of the Merchant's Paybill Number.
        |
        */
        'passkey' => env('MPESA_PASSKEY', 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'),

        /*
        |--------------------------------------------------------------------------
        | Default Transaction Type
        |--------------------------------------------------------------------------
        |
        | This is the Default Transaction Type set on every STK Push request
        |
        */
        'default_transaction_type' => 'CustomerPayBillOnline'
    ],

    /*
    |--------------------------------------------------------------------------
    | C2B Config
    |--------------------------------------------------------------------------
    |
    | This is a fully qualified endpoint that will be be queried by Safaricom's
    | API on completion or failure of the transaction.
    |
    */

    'c2b' => [
        'confirmation_url' => env('MPESA_C2B_CONFIRMATION_URL'),
        'validation_url' => env('MPESA_C2B_VALIDATION_URL'),
        'responseType' => 'Completed',
        'short_code' => env('MPESA_C2B_SHORTCODE', '600256'),
        'test_phone_number' => env('MPESA_TEST_PHONE', '254708374149'),
        'default_command_id' => 'CustomerPayBillOnline'
    ],

    /*
    |--------------------------------------------------------------------------
    | B2C Config
    |--------------------------------------------------------------------------
    |
    | This is a fully qualified endpoint that will be be queried by Safaricom's
    | API on completion or failure of the transaction.
    |
    */

    'b2c' => [
        'initiator_name' => env('MPESA_B2C_INITIATOR_NAME', 'apiop59'),
        'default_command_id' => 'BusinessPayment',
        'initiator_password' => env('MPESA_B2C_INITIATOR_PASSWORD', 'YAL2yKrn'),
        'short_code' => env('MPESA_B2C_SHORTCODE', '602973'),
        'test_phone_number' => env('MPESA_TEST_PHONE', '254708374149'),
        'result_url' => env('MPESA_B2C_RESULT_URL'),
        'timeout_url' => env('MPESA_B2C_TIMEOUT_URL')
    ],

    /*
    |--------------------------------------------------------------------------
    | B2B API Config
    |--------------------------------------------------------------------------
    |
    | This is a fully qualified endpoint that will be be queried by Safaricom's
    | API on completion or failure of the transaction.
    |
    */

    'b2b' => [
        'initiator_name' => env('MPESA_B2B_INITIATOR_NAME', 'testapi0297'),
        'default_command_id' => 'BusinessPayBill',
        'initiator_password' => env('MPESA_B2B_INITIATOR_PASSWORD', 'YAL2yKrn'),
        'short_code' => env('MPESA_B2B_SHORTCODE', '600256'),
        'test_phone_number' => env('MPESA_TEST_PHONE', '254708374149'),
        'result_url' => env('MPESA_B2B_RESULT_URL'),
        'timeout_url' => env('MPESA_B2B_TIMEOUT_URL')
    ],

    /*
    |--------------------------------------------------------------------------
    | Account Balance Config
    |--------------------------------------------------------------------------
    |
    | This is configurations that is required by Safaricom's Account Balance Api
    | 
    |
    */

    'account_balance' => [
        'initiator_name' => env('MPESA_BALANCE_INITIATOR_NAME', 'testapi0297'),
        'initiator_password' => env('MPESA_BALANCE_INITIATOR_PASSWORD', 'YAL2yKrn'),
        'default_command_id' => 'AccountBalance',
        'short_code' => env('MPESA_BALANCE_SHORTCODE', '600256'),
        'result_url' => env('MPESA_BALANCE_RESULT_URL'),
        'timeout_url' => env('MPESA_BALANCE_TIMEOUT_URL')
    ],

    /*
    |--------------------------------------------------------------------------
    | Transaction Status API Config
    |--------------------------------------------------------------------------
    |
    | This is configurations that is required by Safaricom's Transaction Status Api
    | 
    |
    */

    'transaction_status' => [
        'initiator_name' => env('MPESA_STATUS_INITIATOR_NAME', 'testapi0297'),
        'initiator_password' => env('MPESA_STATUS_INITIATOR_PASSWORD', 'YAL2yKrn'),
        'default_command_id' => 'TransactionStatusQuery',
        'short_code' => env('MPESA_STATUS_SHORTCODE', '600256'),
        'result_url' => env('MPESA_STATUS_RESULT_URL'),
        'timeout_url' => env('MPESA_STATUS_TIMEOUT_URL')
    ],

    /*
    |--------------------------------------------------------------------------
    | Reversal API Config
    |--------------------------------------------------------------------------
    |
    | This is configurations that is required by Safaricom's Reversal Api
    | 
    |
    */

    'reversal' => [
        'initiator_name' => env('MPESA_REVERSAL_INITIATOR_NAME', 'testapi0297'),
        'initiator_password' => env('MPESA_REVERSAL_INITIATOR_PASSWORD', 'YAL2yKrn'),
        'default_command_id' => 'TransactionReversal',
        'short_code' => env('MPESA_REVERSAL_SHORTCODE', '600256'),
        'result_url' => env('MPESA_REVERSAL_RESULT_URL'),
        'timeout_url' => env('MPESA_REVERSAL_TIMEOUT_URL')
    ],

    /*
    |--------------------------------------------------------------------------
    | Certificate Path
    |--------------------------------------------------------------------------
    |
    | Path to the certificate file used for encryption
    | Automatically selects based on environment
    |
    */

    'certificate_path' => env('MPESA_ENV', 'sandbox') === 'production'
        ? base_path('config/ProductionCertificate.cer')
        : base_path('config/SandboxCertificate.cer'),
];
